import type { Metadata } from "next";
import "./globals.css";
import { AuthContextProvider } from "@/app/week-9/utils/auth-context";

export const metadata: Metadata = {
  title: "Shopping List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <body className={`antialiased bg-slate-950 px-24`}>{children}</body>
      </AuthContextProvider>
    </html>
  );
}
